### ISSUE TITLE
Ownership of library

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/purescript-handlebars#2]
@wfaler Would you mind moving this library under your own namespace? We're trying to move `purescript-contrib` more towards being general purpose libraries rather than FFI-wrapping-things. 

Also, I don't think @paf31 or I are users of `handlebars` so can't really help with maintenance of the project.

Hopefully soon the [`pursuit`](https://github.com/purescript/pursuit) project will help with the discoverability of libraries the way `purescript-contrib` was originally intended to.

**Comment by paf31** [comment]
@wfaler Ping on this. We're trying to find maintainers for `contrib` libraries. Thanks.

**Comment by wfaler** [comment]
Same here, forked it back. Doubt I will maintain it actively, but can keep it for posterity.

**Comment by paf31** [comment]
Would you like me to just delete the forks then? If I can get it running with 0.7, I might be interested in maintaining `-sammy`, if you like.

**Comment by paf31** [comment]
Same applies here, I'm happy to take over maintainership if need be. I sent a PR to update this.
